spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/CropDB
spring.datasource.username=postgres
spring.datasource.password=2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
